@startuml

skinparam padding 15
skinparam state {
    backgroundColor LightBlue
    borderWidth 5
    padding 20
}

[*] --> INIT

state INIT
INIT : en:
INIT : do:
INIT : ext:

INIT --> GRAB_TIME : TRUE

GRAB_TIME -down-> IDLE : DONE

state IDLE
IDLE : en: Set Minimum Lighting
IDLE : do:
IDLE : ext:

IDLE -right-> IDLE_MOVEMENT : bMovement.Q
IDLE -down-> NIGHTTIME : NTPClient.getNTPTime() == 19:00

state GRAB_TIME
GRAB_TIME : en: Grab time
GRAB_TIME : do: tTime := NTPClient.getNTPTime();
GRAB_TIME : ext:

state IDLE_MOVEMENT
IDLE_MOVEMENT : en:
IDLE_MOVEMENT : do: Cycle some lights, reset tNoMove on bMovement.Q
IDLE_MOVEMENT : ext:

IDLE_MOVEMENT -left-> IDLE : NOT bMovement.Q \nAND\ntNoMove#2M
IDLE_MOVEMENT -right-> ACT : bBill.Q \nOR\nbCoin.Q

state NIGHTTIME
NIGHTTIME : en: Lights Off, Crib Off
NIGHTTIME : do: Poll Time every 10Mins
NIGHTTIME : ext:

NIGHTTIME --> IDLE : NTPClient.getNTPTime() == 08:00

state ACT
ACT : en: 
ACT : do: Cycle Lights, Crib & Sound
ACT : ext:

ACT --> IDLE_MOVEMENT : DONE

state ERROR
ERROR : en: Ligths Off, Stop Crib
ERROR : do:
ERROR : ext:

ERROR --> INIT : bErrorACK.Q

note right of ERROR
  out of every state
end note
@enduml
